import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                'surface': '#f8f9ff',
                'surface-dim': '#cbdbf5',
                'surface-bright': '#f8f9ff',
                'surface-variant': '#d3e4fe',
                'surface-tint': '#465f88',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#eff4ff',
                'surface-container': '#e5eeff',
                'surface-container-high': '#dce9ff',
                'surface-container-highest': '#d3e4fe',
                'on-surface': '#0b1c30',
                'on-surface-variant': '#44474e',
                'inverse-surface': '#213145',
                'inverse-on-surface': '#eaf1ff',
                'background': '#f8f9ff',
                'on-background': '#0b1c30',
                'outline': '#74777f',
                'outline-variant': '#c4c6cf',
                'primary': '#002046',
                'primary-container': '#1b365d',
                'on-primary': '#ffffff',
                'on-primary-container': '#87a0cd',
                'primary-fixed': '#d6e3ff',
                'primary-fixed-dim': '#aec7f7',
                'on-primary-fixed': '#001b3d',
                'on-primary-fixed-variant': '#2e476f',
                'inverse-primary': '#aec7f7',
                'secondary': '#006c4a',
                'secondary-container': '#82f5c1',
                'on-secondary': '#ffffff',
                'on-secondary-container': '#00714e',
                'secondary-fixed': '#85f8c4',
                'secondary-fixed-dim': '#68dba9',
                'on-secondary-fixed': '#002114',
                'on-secondary-fixed-variant': '#005137',
                'tertiary': '#361900',
                'tertiary-container': '#552b00',
                'on-tertiary': '#ffffff',
                'on-tertiary-container': '#eb851c',
                'tertiary-fixed': '#ffdcc3',
                'tertiary-fixed-dim': '#ffb77d',
                'on-tertiary-fixed': '#2f1500',
                'on-tertiary-fixed-variant': '#6e3900',
                'error': '#ba1a1a',
                'error-container': '#ffdad6',
                'on-error': '#ffffff',
                'on-error-container': '#93000a',
            },
            spacing: {
                'margin': '1rem',
                'margin-md': '1.5rem',
                'margin-lg': '2rem',
                'gutter': '1rem',
                'gutter-lg': '1.5rem',
                'space-xs': '0.25rem',
                'space-sm': '0.5rem',
                'space-md': '0.75rem',
                'space-lg': '1rem',
                'space-xl': '1.5rem',
            },
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                'headline-sm': ['Inter', 'sans-serif'],
                'headline-md': ['Inter', 'sans-serif'],
                'headline-lg': ['Inter', 'sans-serif'],
                'display-lg': ['Inter', 'sans-serif'],
                'body-sm': ['Inter', 'sans-serif'],
                'body-md': ['Inter', 'sans-serif'],
                'body-lg': ['Inter', 'sans-serif'],
                'label-sm': ['Inter', 'sans-serif'],
                'label-md': ['Inter', 'sans-serif'],
                'label-lg': ['Inter', 'sans-serif'],
                'data-mono': ['Inter', 'monospace'],
            },
            fontSize: {
                'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
                'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
                'display-lg': ['30px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
                'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'body-lg': ['15px', { lineHeight: '22px', fontWeight: '400' }],
                'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
                'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
                'label-lg': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '600' }],
                'data-mono': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
            }
        },
    },

    plugins: [forms],
};

